import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import { Link } from "react-router-dom";



import "./AfterLife.css";

import coin from "assets/Home/a1.svg";
import shop from "assets/Home/a2.svg";
// import percentage from "assets/Home/a3.svg";
// import chart from "assets/Home/a4.svg";

import image1 from "assets/Home/img1.jpg";
import image2 from "assets/Home/img2.jpg";
import PrimaryButton from "components/PrimaryButton";

import useWindowDimensions from "hooks/windowDimensions";

function AfterLife({handleKnowMore}) {

  const { width } = useWindowDimensions();
  const isSmallScreen = width < 992;

  const listItems = [
    { icon: coin, title: "AfterCoin", width: "50", height: "50", to: "/after-coin" },
    { icon: shop, title: "Market Place", width: "60", height: "60", to: "/market-place" },
    // { icon: percentage, title: "DAO", width: "50", height: "50" },
    // { icon: chart, title: "DiFi App", width: "60", height: "60" },
  ];
  return (
    <Container className="after-life"> 
      <Row>
        <Col lg={5}>  
          <h2 >UNBOUND FREEDOM</h2>
          <h3 >
            Your {!isSmallScreen && <br />}
            Virtual {isSmallScreen && <br />} Afterlife
          </h3>
          <p className="highlight" >
            The Afterverse provides the unbound freedom of the life after death
            in a meta verse that are bound by ruleless rules that defy gaming
            physics and the laws of exitence.
          </p>
          <p >
            Afterverse provides progressive financial incentives generated by
            the contrubutions of the open creative community. It enables a
            strong and prosperous community who will create and play in the
            Afterverse for AfterCoin (AC) which will be the official token for
            governance.
          </p>
          <p className="items" >
            {listItems.map((item, idx) => {
              return (
                <Link className="items-list" to={item.to}>
                  <span className="item" key={idx}>
                    <span className="item-container">
                      <img
                        src={item.icon}
                        width={item.width}
                        height={item.height}
                        alt={item.title}
                      />
                      <span>{item.title}</span>
                    </span>
                  </span>
                </Link>
              );
            })}
          </p>
          <div >
          {!isSmallScreen && <PrimaryButton onClick={handleKnowMore} >Know More</PrimaryButton>}

          </div>
        </Col>
        {!isSmallScreen && (
          <Col className="image-section" >
            <img
              className="door-path"
              src={image1}
              alt="man-before-door-path"
            />
            <img className="silver-coin" src={image2} alt="silver-coin" />
          </Col>
        )}
      </Row>
      {isSmallScreen && (
        <Row>
          <img src={image1} alt="man-before-door-path" />
        </Row>
      )}
    </Container>
  );
}

export default AfterLife;
